import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "./models/product.model.js";

dotenv.config();

const dummyProducts = [
    {
        name: "Potato 500g",
        category: "Vegetables",
        price: 25,
        offerPrice: 20,
        image: ["potato_1.png", "potato_2.png", "potato_3.png", "potato_4.png"],
        description: [
            "Fresh and organic",
            "Rich in carbohydrates",
            "Ideal for curries and fries",
        ],
        inStock: true,
    },
    {
        name: "Tomato 1 kg",
        category: "Vegetables",
        price: 40,
        offerPrice: 35,
        image: ["tomato_image.png"],
        description: [
            "Juicy and ripe",
            "Rich in Vitamin C",
            "Perfect for salads and sauces",
            "Farm fresh quality",
        ],
        inStock: true,
    },
    {
        name: "Carrot 500g",
        category: "Vegetables",
        price: 30,
        offerPrice: 28,
        image: ["carrot_image.png"],
        description: [
            "Sweet and crunchy",
            "Good for eyesight",
            "Ideal for juices and salads",
        ],
        inStock: true,
    },
    {
        name: "Spinach 500g",
        category: "Vegetables",
        price: 18,
        offerPrice: 15,
        image: ["spinach.png"],
        description: [
            "Rich in iron",
            "High in vitamins",
            "Perfect for soups and salads",
        ],
        inStock: true,
    },
    {
        name: "Onion 500g",
        category: "Vegetables",
        price: 22,
        offerPrice: 19,
        image: ["onion.png"],
        description: [
            "Fresh and pungent",
            "Perfect for cooking",
            "A kitchen staple",
        ],
        inStock: true,
    },
    {
        name: "Apple 1 kg",
        category: "Fruits",
        price: 120,
        offerPrice: 110,
        image: ["apple_image.png"],
        description: [
            "Crisp and juicy",
            "Rich in fiber",
            "Boosts immunity",
            "Perfect for snacking and desserts",
            "Organic and farm fresh",
        ],
        inStock: true,
    },
    {
        name: "Orange 1 kg",
        category: "Fruits",
        price: 80,
        offerPrice: 75,
        image: ["orange_image.png"],
        description: [
            "Juicy and sweet",
            "Rich in Vitamin C",
            "Perfect for juices and salads",
        ],
        inStock: true,
    },
    {
        name: "Banana 1 kg",
        category: "Fruits",
        price: 50,
        offerPrice: 45,
        image: ["banana.png"],
        description: [
            "Sweet and ripe",
            "High in potassium",
            "Great for smoothies and snacking",
        ],
        inStock: true,
    },
    {
        name: "Mango 1 kg",
        category: "Fruits",
        price: 150,
        offerPrice: 140,
        image: ["mango.png"],
        description: [
            "Sweet and flavorful",
            "Perfect for smoothies and desserts",
            "Rich in Vitamin A",
        ],
        inStock: true,
    },
    {
        name: "Grapes 500g",
        category: "Fruits",
        price: 70,
        offerPrice: 65,
        image: ["grapes.png"],
        description: [
            "Fresh and juicy",
            "Rich in antioxidants",
            "Perfect for snacking and fruit salads",
        ],
        inStock: true,
    },
    {
        name: "Amul Milk 1L",
        category: "Dairy",
        price: 60,
        offerPrice: 55,
        image: ["amul_milk_image.png"],
        description: [
            "Pure and fresh",
            "Rich in calcium",
            "Ideal for tea, coffee, and desserts",
            "Trusted brand quality",
        ],
        inStock: true,
    },
    {
        name: "Paneer 200g",
        category: "Dairy",
        price: 90,
        offerPrice: 85,
        image: ["paneer_image.png"],
        description: [
            "Soft and fresh",
            "Rich in protein",
            "Ideal for curries and snacks",
        ],
        inStock: true,
    },
    {
        name: "Eggs 12 pcs",
        category: "Dairy",
        price: 90,
        offerPrice: 85,
        image: ["eggs_image.png"],
        description: [
            "Farm fresh",
            "Rich in protein",
            "Ideal for breakfast and baking",
        ],
        inStock: true,
    },
    {
        name: "Cheese 200g",
        category: "Dairy",
        price: 140,
        offerPrice: 130,
        image: ["cheese_image.png"],
        description: [
            "Creamy and delicious",
            "Perfect for pizzas and sandwiches",
            "Rich in calcium",
        ],
        inStock: true,
    },
    {
        name: "Coca-Cola 1.5L",
        category: "Drinks",
        price: 80,
        offerPrice: 75,
        image: ["coca_cola_image.png"],
        description: [
            "Refreshing and fizzy",
            "Perfect for parties and gatherings",
            "Best served chilled",
        ],
        inStock: true,
    },
    {
        name: "Pepsi 1.5L",
        category: "Drinks",
        price: 78,
        offerPrice: 73,
        image: ["pepsi_image.png"],
        description: [
            "Chilled and refreshing",
            "Perfect for celebrations",
            "Best served cold",
        ],
        inStock: true,
    },
    {
        name: "Sprite 1.5L",
        category: "Drinks",
        price: 79,
        offerPrice: 74,
        image: ["sprite.png"],
        description: [
            "Refreshing citrus taste",
            "Perfect for hot days",
            "Best served chilled",
        ],
        inStock: true,
    },
    {
        name: "Fanta 1.5L",
        category: "Drinks",
        price: 77,
        offerPrice: 72,
        image: ["fanta.png"],
        description: [
            "Sweet and fizzy",
            "Great for parties and gatherings",
            "Best served cold",
        ],
        inStock: true,
    },
    {
        name: "7 Up 1.5L",
        category: "Drinks",
        price: 76,
        offerPrice: 71,
        image: ["seven_up.png"],
        description: [
            "Refreshing lemon-lime flavor",
            "Perfect for refreshing",
            "Best served chilled",
        ],
        inStock: true,
    },
    {
        name: "Basmati Rice 5kg",
        category: "Grains",
        price: 550,
        offerPrice: 520,
        image: ["basmati_rice_image.png"],
        description: [
            "Long grain and aromatic",
            "Perfect for biryani and pulao",
            "Premium quality",
        ],
        inStock: true,
    },
    {
        name: "Wheat Flour 5kg",
        category: "Grains",
        price: 250,
        offerPrice: 230,
        image: ["wheat_flour_image.png"],
        description: [
            "High-quality whole wheat",
            "Soft and fluffy rotis",
            "Rich in nutrients",
        ],
        inStock: true,
    },
    {
        name: "Organic Quinoa 500g",
        category: "Grains",
        price: 450,
        offerPrice: 420,
        image: ["quinoa_image.png"],
        description: [
            "High in protein and fiber",
            "Gluten-free",
            "Rich in vitamins and minerals",
        ],
        inStock: true,
    },
    {
        name: "Brown Rice 1kg",
        category: "Grains",
        price: 120,
        offerPrice: 110,
        image: ["brown_rice_image.png"],
        description: [
            "Whole grain and nutritious",
            "Helps in weight management",
            "Good source of magnesium",
        ],
        inStock: true,
    },
    {
        name: "Barley 1kg",
        category: "Grains",
        price: 150,
        offerPrice: 140,
        image: ["barley_image.png"],
        description: [
            "Rich in fiber",
            "Helps improve digestion",
            "Low in fat and cholesterol",
        ],
        inStock: true,
    },
    {
        name: "Brown Bread 400g",
        category: "Bakery",
        price: 40,
        offerPrice: 35,
        image: ["brown_bread_image.png"],
        description: [
            "Soft and healthy",
            "Made from whole wheat",
            "Ideal for breakfast and sandwiches",
        ],
        inStock: true,
    },
    {
        name: "Butter Croissant 100g",
        category: "Bakery",
        price: 50,
        offerPrice: 45,
        image: ["butter_croissant_image.png"],
        description: [
            "Flaky and buttery",
            "Freshly baked",
            "Perfect for breakfast or snacks",
        ],
        inStock: true,
    },
    {
        name: "Chocolate Cake 500g",
        category: "Bakery",
        price: 350,
        offerPrice: 325,
        image: ["chocolate_cake_image.png"],
        description: [
            "Rich and moist",
            "Made with premium cocoa",
            "Ideal for celebrations and parties",
        ],
        inStock: true,
    },
    {
        name: "Whole Bread 400g",
        category: "Bakery",
        price: 45,
        offerPrice: 40,
        image: ["whole_wheat_bread_image.png"],
        description: [
            "Healthy and nutritious",
            "Made with whole wheat flour",
            "Ideal for sandwiches and toast",
        ],
        inStock: true,
    },
    {
        name: "Vanilla Muffins 6 pcs",
        category: "Bakery",
        price: 100,
        offerPrice: 90,
        image: ["vanilla_muffins_image.png"],
        description: [
            "Soft and fluffy",
            "Perfect for a quick snack",
            "Made with real vanilla",
        ],
        inStock: true,
    },
    {
        name: "Maggi Noodles 280g",
        category: "Instant",
        price: 55,
        offerPrice: 50,
        image: ["maggi_image.png"],
        description: [
            "Instant and easy to cook",
            "Delicious taste",
            "Popular among kids and adults",
        ],
        inStock: true,
    },
    {
        name: "Top Ramen 270g",
        category: "Instant",
        price: 45,
        offerPrice: 40,
        image: ["top_ramen_image.png"],
        description: [
            "Quick and easy to prepare",
            "Spicy and flavorful",
            "Loved by college students and families",
        ],
        inStock: true,
    },
    {
        name: "Knorr Cup Soup 70g",
        category: "Instant",
        price: 35,
        offerPrice: 30,
        image: ["knorr_soup_image.png"],
        description: [
            "Convenient for on-the-go",
            "Healthy and nutritious",
            "Variety of flavors",
        ],
        inStock: true,
    },
    {
        name: "Yippee Noodles 260g",
        category: "Instant",
        price: 50,
        offerPrice: 45,
        image: ["yippee_image.png"],
        description: [
            "Non-fried noodles for healthier choice",
            "Tasty and filling",
            "Convenient for busy schedules",
        ],
        inStock: true,
    },
    {
        name: "Oats Noodles 72g",
        category: "Instant",
        price: 40,
        offerPrice: 35,
        image: ["maggi_oats_image.png"],
        description: [
            "Healthy alternative with oats",
            "Good for digestion",
            "Perfect for breakfast or snacks",
        ],
        inStock: true,
    },
    // Beverages
    {
        name: "Coca-Cola 500ml",
        category: "Beverages",
        price: 40,
        offerPrice: 35,
        image: ["coca_cola_image.png"],
        description: [
            "Refreshing cola drink",
            "Ice-cold goodness",
            "Perfect for meals and celebrations",
        ],
        inStock: true,
    },
    {
        name: "Pepsi 500ml",
        category: "Beverages",
        price: 40,
        offerPrice: 35,
        image: ["pepsi_image.png"],
        description: [
            "Crisp and refreshing",
            "Iconic cola taste",
            "Great for any occasion",
        ],
        inStock: true,
    },
    {
        name: "Sprite 500ml",
        category: "Beverages",
        price: 40,
        offerPrice: 35,
        image: ["sprite.png"],
        description: [
            "Lemon-lime flavored soda",
            "Clear and refreshing",
            "Quenches thirst instantly",
        ],
        inStock: true,
    },
    {
        name: "Fanta Orange 500ml",
        category: "Beverages",
        price: 40,
        offerPrice: 35,
        image: ["fanta.png"],
        description: [
            "Fruity and fun",
            "Bright orange flavor",
            "Perfect for parties",
        ],
        inStock: true,
    },
    {
        name: "7-Up 500ml",
        category: "Beverages",
        price: 40,
        offerPrice: 35,
        image: ["seven_up.png"],
        description: [
            "Lemon-lime carbonated drink",
            "Clean and crisp taste",
            "Refreshing alternative",
        ],
        inStock: true,
    },
    // Namkeens
    {
        name: "Biscuit Mix 200g",
        category: "Namkeens",
        price: 80,
        offerPrice: 70,
        image: ["wheat_flour_image.png"],
        description: [
            "Crispy and tasty",
            "Perfect tea-time snack",
            "Pack of assorted biscuits",
        ],
        inStock: true,
    },
    {
        name: "Namkeen Mix 250g",
        category: "Namkeens",
        price: 120,
        offerPrice: 100,
        image: ["maggi_image.png"],
        description: [
            "Traditional spiced snack mix",
            "Crunchy and savory",
            "Great for snacking anytime",
        ],
        inStock: true,
    },
    {
        name: "Fried Potato Chips 150g",
        category: "Namkeens",
        price: 60,
        offerPrice: 50,
        image: ["potato_1.png"],
        description: [
            "Light and crispy",
            "Salted goodness",
            "Perfect snack for everyone",
        ],
        inStock: true,
    },
    {
        name: "Popcorn Caramel 100g",
        category: "Namkeens",
        price: 70,
        offerPrice: 60,
        image: ["maggi_image.png"],
        description: [
            "Sweet and salty combination",
            "Perfect for movie nights",
            "Freshly popped goodness",
        ],
        inStock: true,
    },
    {
        name: "Chakli Spicy 200g",
        category: "Namkeens",
        price: 90,
        offerPrice: 80,
        image: ["wheat_flour_image.png"],
        description: [
            "Spiral-shaped savory snack",
            "Crispy and flavorful",
            "Traditional Indian favorite",
        ],
        inStock: true,
    },
    // Chocolates
    {
        name: "Dairy Milk 40g",
        category: "Chocolates",
        price: 50,
        offerPrice: 45,
        image: ["dairy_milk_image.png"],
        description: [
            "Smooth and creamy milk chocolate",
            "Iconic taste loved by all",
            "Perfect indulgence",
        ],
        inStock: true,
    },
    {
        name: "Ferrero Rocher 48g",
        category: "Chocolates",
        price: 120,
        offerPrice: 110,
        image: ["ferrero_rocher_image.png"],
        description: [
            "Crispy wafer layers",
            "Golden hazelnut filling",
            "Luxury chocolate experience",
        ],
        inStock: true,
    },
    {
        name: "Lindt Truffle 37g",
        category: "Chocolates",
        price: 100,
        offerPrice: 90,
        image: ["lindt_truffle_image.png"],
        description: [
            "Premium Swiss chocolate",
            "Smooth melting truffles",
            "Delicate flavor",
        ],
        inStock: true,
    },
    {
        name: "Toblerone 50g",
        category: "Chocolates",
        price: 80,
        offerPrice: 70,
        image: ["lindt_truffle_image.png"],
        description: [
            "Nougat and almond clusters",
            "Iconic triangular shape",
            "Swiss chocolate tradition",
        ],
        inStock: true,
    },
    {
        name: "Dark Chocolate 45g",
        category: "Chocolates",
        price: 90,
        offerPrice: 80,
        image: ["dairy_milk_image.png"],
        description: [
            "Rich and intense flavor",
            "70% cocoa content",
            "Pure chocolate bliss",
        ],
        inStock: true,
    },
];


const seedDB = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI || "mongodb://localhost:27017/grocery-app");
        console.log("MongoDB connected for seeding...");

        await Product.deleteMany();
        console.log("Cleared existing products from database.");

        await Product.insertMany(dummyProducts);
        console.log("Successfully seeded dummy products into database!");

        process.exit(0);
    } catch (error) {
        console.error("Error seeding database:", error);
        process.exit(1);
    }
};

seedDB();
